version: "3.9"
services:
  postgres: 
    container_name: postgres_container
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: yourPassword
      POSTGRES_DB: "USER_INFO"
    ports: 
      - "5432:5432"
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com 
      PGADMIN_DEFAULT_PASSWORD: root
    ports: 
      - 8080:80
      
